runtime: nodejs20
env: standard
instanceClass: F2
service: default

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 10
  timeout_sec: 10
  healthy_threshold: 2
  unhealthy_threshold: 3
  initial_delay_sec: 300
  port: 3000
  type: HTTP
  path: /

# Environment variables for Next.js
env_variables:
  NODE_ENV: "production"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "kollectcare-rwe-study"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "kollectcare-rwe-study.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyDAn3llTqhmCmysQ0_lcX79RvuJsQMB2ks"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "kollectcare-rwe-study.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "716627719667"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:716627719667:web:a828412396c68af35b8e86"

# Performance settings
max_instances: 10
min_instances: 1

