#!/usr/bin/env python3
"""
Google Cloud Billing Deep Analysis
Identifies exact services, projects, and cost changes
"""

import json
import os
from datetime import datetime, timedelta
from pathlib import Path

print("╔════════════════════════════════════════════════════════════════════════════╗")
print("║             GCP BILLING DEEP ANALYSIS - PROJECT INVESTIGATION             ║")
print("╚════════════════════════════════════════════════════════════════════════════╝\n")

# Since we don't have direct API access yet, let's create an analysis based on 
# what we KNOW from your screenshot and provide guidance

print("📊 ANALYSIS BASED ON YOUR BILLING SCREENSHOT\n")
print("=" * 80)
print("CURRENT CHARGES IDENTIFIED")
print("=" * 80 + "\n")

services_identified = {
    "Cloud Run": {
        "cost": "Primary charge driver",
        "status": "RUNNING",
        "details": "You mentioned Cloud Run has 'maximum' - this may indicate high request volume or sustained compute",
        "monthly_estimate": "Unknown - appears significant"
    },
    "Cloud Logging": {
        "cost": "$490+ (visible in screenshot)",
        "status": "ACTIVE",
        "details": "Logging service running continuously",
        "monthly_estimate": "~$490-870/month"
    },
    "Other Services": {
        "cost": "Unknown",
        "status": "ACTIVE",
        "details": "Multiple projects visible in dropdown",
        "monthly_estimate": "Variable"
    }
}

for service, details in services_identified.items():
    print(f"🔹 {service}")
    print(f"   Cost: {details['cost']}")
    print(f"   Status: {details['status']}")
    print(f"   Details: {details['details']}")
    print(f"   Estimate: {details['monthly_estimate']}\n")

print("\n" + "=" * 80)
print("HOW TO GET DETAILED BREAKDOWN FROM GOOGLE CLOUD CONSOLE")
print("=" * 80 + "\n")

steps = [
    {
        "step": 1,
        "title": "Go to Billing > Reports",
        "url": "https://console.cloud.google.com/billing/reports"
    },
    {
        "step": 2,
        "title": "Click 'Group by Project Hierarchy' and change to 'Group by SERVICE'",
        "details": "This shows exactly which services are charging"
    },
    {
        "step": 3,
        "title": "Change time range to see monthly breakdown",
        "details": "Select last 3 months to see trend"
    },
    {
        "step": 4,
        "title": "Download CSV with 'Download CSV' button",
        "details": "Get detailed line-item billing data"
    },
    {
        "step": 5,
        "title": "Analyze SKU (Stock Keeping Unit) details",
        "details": "Each line shows: Service > SKU > Description > Cost"
    }
]

for item in steps:
    print(f"Step {item['step']}: {item['title']}")
    print(f"           └─ {item.get('details', item.get('url', ''))}\n")

print("\n" + "=" * 80)
print("KEY METRICS TO CHECK IN YOUR BILLING CSV")
print("=" * 80 + "\n")

metrics = {
    "Cloud Run": [
        "vCPU seconds (number of computation seconds used)",
        "Memory GB-seconds (RAM consumed)",
        "Number of requests (if any quota exceeded)",
        "Cloud Logging ingestion (logs generated by Cloud Run)"
    ],
    "Cloud Logging": [
        "Log volume in GB (overage beyond 50GB free)",
        "Log retention charges",
        "Log analysis/BigQuery export costs"
    ],
    "Other Potential Charges": [
        "Firestore storage (if > 1GB)",
        "Firestore operations (if > free tier)",
        "Network egress (if > 1GB/month)",
        "Cloud Storage (if using buckets)"
    ]
}

for service, items in metrics.items():
    print(f"📋 {service}:")
    for item in items:
        print(f"   • {item}")
    print()

print("\n" + "=" * 80)
print("WHAT YOUR SCREENSHOT SHOWS (ANALYSIS)")
print("=" * 80 + "\n")

screenshot_analysis = """
From your image, I can see:

1. BILLING ACCOUNT: "My Billing Account"
   └─ Status: PAY-AS-YOU-GO (no free trial credit remaining)

2. TIME RANGE: October 1, 2025 - May 31, 2026
   └─ Shows 8 months of billing history
   └─ Chart shows charges increasing over time (blue bars higher in later months)

3. PROJECTS SHOWN:
   • Kollectcare RWE Study (kollectcare-rwe-study)
   • Multiple other projects in the dropdown

4. SERVICES IDENTIFIED:
   ✓ Cloud Logging - ₹490.44+ (visible in Services list)
   ✓ Cloud Run - Currently selected (appears to be primary charge)
   ✓ Cloud Pub/Sub - Listed (may have charges)
   ✓ Cloud Run Functions - Listed
   ✓ Cloud Storage - Listed

5. TOTAL VISIBLE: ₹870.44 (subtotal for selected filters)

6. KEY OBSERVATION: The chart shows increasing trend from Oct 2025 to May 2026
   └─ This suggests services were added or increased over time
   └─ October-November: Lower charges
   └─ December onwards: Significant increase
"""

print(screenshot_analysis)

print("\n" + "=" * 80)
print("RECOMMENDED INVESTIGATION STEPS")
print("=" * 80 + "\n")

recommendations = [
    {
        "priority": "🔴 CRITICAL",
        "action": "Check Cloud Run cost metrics",
        "details": [
            "1. Go to Cloud Run dashboard",
            "2. Click 'METRICS' tab",
            "3. Check: vCPU seconds, Memory GB-seconds, Request count",
            "4. If numbers are very high, you have a memory leak or infinite loop"
        ]
    },
    {
        "priority": "🟠 HIGH",
        "action": "Review Cloud Logging volume",
        "details": [
            "1. Go to Cloud Logging > Logs Explorer",
            "2. Group by resource type",
            "3. Check which resources are generating logs",
            "4. Health checks (10-second intervals) may be generating logs"
        ]
    },
    {
        "priority": "🟡 MEDIUM",
        "action": "Check for background jobs/processes",
        "details": [
            "1. Review Cloud Scheduler jobs",
            "2. Check Cloud Tasks queues",
            "3. Look for any automated processes that run 24/7",
            "4. These could be continuously calling Cloud Run"
        ]
    },
    {
        "priority": "🔵 LOW",
        "action": "Verify data storage costs",
        "details": [
            "1. Firestore: Should be ~$0 (your usage is minimal)",
            "2. Cloud Storage: Check if backups are stored",
            "3. Database: Any BigQuery queries running?"
        ]
    }
]

for rec in recommendations:
    print(f"{rec['priority']} - {rec['action']}")
    for detail in rec['details']:
        print(f"   {detail}")
    print()

print("\n" + "=" * 80)
print("EXPORT YOUR BILLING DATA FOR DETAILED ANALYSIS")
print("=" * 80 + "\n")

export_guide = """
To get EXACT breakdown of what changed:

1. Go to: https://console.cloud.google.com/billing/reports
2. Click "Download CSV" button
3. This downloads detailed billing data with:
   - SKU ID (exact service identifier)
   - SKU Description (what was charged for)
   - Amount (cost per unit)
   - Quantity (how much was used)
   - Total (amount × quantity)

4. Import CSV into Excel/Sheets and sort by:
   - Service name (to group by service)
   - Total cost (descending - most expensive first)
   - Month (to see trend)

5. Share the CSV or key lines and I can analyze exactly what changed
"""

print(export_guide)

print("\n" + "=" * 80)
print("✅ NEXT STEPS")
print("=" * 80 + "\n")

print("""
1. IMMEDIATE (Next 5 minutes):
   • Export billing CSV from Google Cloud Console
   • Share the CSV data with me
   • I'll analyze EXACTLY which services changed and why

2. SHORT-TERM (Next 30 minutes):
   • Review Cloud Run logs for errors/infinite loops
   • Check if health checks are causing excessive logging
   • Verify no background jobs are continuously running

3. SOLUTION (1-2 hours):
   • Migrate to Cloud Run (0-minute cold start acceptable for pilot)
   • Or optimize App Engine (if you want to stay on it)
   • Result: $36/month → $0/month

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📍 CRITICAL PATH:
   App Engine always-on ($36/month) → Cloud Run free tier ($0/month)
   🎯 SAVES: $432/year
""")

print("\n" + ("=" * 80))
